version: '3.4'

services:
  webmtomp4telegrambot:
    image: ${DOCKER_REGISTRY-}webmtomp4telegrambot
    build:
      context: .
      dockerfile: WebMToMP4TelegramBot/Dockerfile
    ports:
      - "8083:80"
    volumes:
      - /var/log/bots:/app/log
  telegramapi:
    image: julyighor/telegram-bot-api
    ports:
      - "8081:8081" 